#!/usr/bin/env bash

# Based on https://github.com/hlissner/dotfiles/blob/f0642a0f56c37029507b7ae2f67a2ec4d7974f5c/deploy

set -e

DOTFILES="$(cd $(dirname "${BASH_SOURCE:-${(%):-%x}}") && pwd -P)"
PREFIX="${PREFIX:-/mnt}"
NIXOSPREFIX="${PREFIX}/etc/nixos"
NIXOSFLAGS="-I 'config=$DOTFILES/config' -I 'modules=$DOTFILES/modules' -I 'packages=$DOTFILES/packages'"
HOST=${1:-${HOST:-orithena}}

if [ ! -f "$DOTFILES/hosts/$HOST/default.nix" ]; then
  >&2 echo "No configuration exists for host '$HOST'"
  exit 1
fi

mkdir -p "$NIXOSPREFIX"
echo "import ../dotfiles/hosts/$HOST" > "$NIXOSPREFIX/configuration.nix"

nix-channel --add https://nixos.org/channels/nixos-20.03 nixos
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
nix-channel --update

nixos-install --root "$PREFIX" $NIXOSFLAGS
