#!/usr/bin/env bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

function install_packages() {
    local packages=("$@")

    for package in "${packages[@]}";
    do
        sudo zypper install --non-interactive --auto-agree-with-licenses "$package"
    done
}


function install_flatpak_packages() {
    local packages=("$@")

    for package in "${packages[@]}";
    do
        flatpak -y install "$package"
    done
}

core=(
    ca-certificates
    coreutils
    curl
    git
    gnupg
    openssh-client
    stow
    unzip
    neovim
    wget
)

# TODO iosevka-nerd gnome-tweaks yubikey-personalization-gui
desktop=(
    bitwarden
    calibre
    emacs
    extension-manager
    iosevka-fonts
    mpv
    obsidian
    protonvpn-gui
    signal-desktop
    transmission
    veracrypt
    zathura
    zotero
)

# TODO bandwhich joshuto
shell=(
    wezterm
    fish

    atuin
    bat
    bottom
    direnv
    dog
    dust
    duf
    exa
    fd
    fzf
    gnupg
    htop
    httpie
    hyperfine
    jq
    lazygit
    links
    procs
    ripgrep
    rsync
    sd
    tcpdump
    tokei
    tree
    viddy
    zoxide
)

flatpak=(
    com.dropbox.Client
    com.slack.Slack
    com.spotify.Client
)

sudo zypper addrepo -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/' packman
sudo zypper addrepo https://download.opensuse.org/repositories/editors/openSUSE_Tumbleweed/editors.repo
sudo zypper addrepo https://download.opensuse.org/repositories/openSUSE:Factory/standard/openSUSE:Factory.repo

sudo zypper ref --non-interactive
sudo zypper dup --non-interactive --auto-agree-with-licenses
sudo zypper dist-upgrade --from packman --allow-vendor-change --non-interactive --auto-agree-with-licenses

# codecs
sudo zypper install --from packman --non-interactive --auto-agree-with-licenses ffmpeg gstreamer-plugins-{good,bad,ugly,libav} libavcodec vlc-codecs
install_packages "${core[@]}"
install_packages "${shell[@]}"
install_packages "${desktop[@]}"

flatpak update
install_flatpak_packages "${flatpak[@]}"

mkdir -p ~/{bin,.config}
stow --target=/home/gsnewmark/bin bin
stow --dir=config --target=/home/gsnewmark browser
stow --dir=config --target=/home/gsnewmark desktop
stow --dir=config --target=/home/gsnewmark dev
stow --dir=config --target=/home/gsnewmark emacs
stow --dir=config --target=/home/gsnewmark shell
