#!/usr/bin/env bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

function setup_ppas() {
    local ppas=("$@")

    for ppa in "${ppas[@]}";
    do
        sudo add-apt-repository -y "$ppa"
    done

    sudo apt update
}

function install_apt_packages() {
    local packages=("$@")

    for package in "${packages[@]}";
    do
        sudo apt -y install "$package"
    done
}

function install_flatpak_packages() {
    local packages=("$@")

    for package in "${packages[@]}";
    do
        flatpak -y install "$package"
    done
}

ppas=(
    ppa:unit193/encryption # veracrypt
)

core=(
    fish
    ca-certificates
    coreutils
    curl
    git
    gnupg
    openssh-client
    stow
    unzip
    neovim
    wget
)

# TODO protonvpn-gui
desktop=(
    calibre
    mpv
    steam
    transmission
    ubuntu-restricted-extras
    veracrypt
    yubikey-personalization
    zathura
)

# TODO bandwhich joshuto bottom dog hyperfine procs viddy du-dust tokei
shell=(
    wezterm

    bat
    direnv
    duf
    eza
    fd-find
    fzf
    gnupg
    htop
    httpie
    jq
    links
    ripgrep
    rsync
    tcpdump
    tree
    zoxide
)

flatpak=(
    com.bitwarden.desktop
    com.dropbox.Client
    com.mojang.Minecraft
    com.slack.Slack
    com.spotify.Client
    md.obsidian.Obsidian
    org.signal.Signal
    org.zotero.Zotero
)

sudo apt update
sudo apt upgrade
flatpak update

# WezTerm
curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list

# Eza
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list

setup_ppas "${ppas[@]}"
install_apt_packages "${core[@]}"
install_apt_packages "${shell[@]}"
bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh) # atuin

# Lazygit
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
sudo install lazygit /usr/local/bin

install_apt_packages "${desktop[@]}"

# Zed
curl -f https://zed.dev/install.sh | sh

sudo apt clean
sudo apt autoremove --purge

install_flatpak_packages "${flatpak[@]}"

# bootstrap dotfiles
mkdir -p ~/{bin,.config}
stow --target=/home/gsnewmark/bin bin
stow --dir=config --target=/home/gsnewmark desktop
stow --dir=config --target=/home/gsnewmark dev
stow --dir=config --target=/home/gsnewmark emacs
stow --dir=config --target=/home/gsnewmark shell

# install font
wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/IosevkaTerm.zip \
    && cd ~/.local/share/fonts \
    && unzip IosevkaTerm.zip \
    && rm IosevkaTerm.zip \
    && fc-cache -fv

# change shell
chsh -s /usr/bin/fish
