(live-load-config-file "spelling-conf.el")
(live-load-config-file "color-themes-conf.el")
(live-load-config-file "misc-conf.el")
(live-load-config-file "lang-conf.el")
(live-load-config-file "org-conf.el")
(live-load-config-file "bindings.el")
(live-load-config-file "input-method.el")
