{:user {:dependencies [[slamhound "1.5.5"]]
        :plugins [[cider/cider-nrepl "0.8.2-SNAPSHOT"]
                  [refactor-nrepl "0.2.2"]
                  [lein-try "0.4.3"]
                  [lein-ancient "0.6.0-SNAPSHOT"]
                  [lein-bikeshed "0.1.8"]
                  [lein-kibit "0.0.8"]
                  [jonase/eastwood "0.2.0"]
                  [lein-gorilla "0.3.3"]]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
